### PR TITLE
Mobile Optimization

### PR DESCRIPTION
**Pull request by KadenZipfel**
I've optimized the landing page for mobile screens. It's very possible that the spacing is imperfect in certain areas, so reviews are much appreciated.

### CODE REVIEW

**Comment by pimato** [comment]
Hey @KadenZipfel do you know why the paddings on the left and right are off when testing:
Screenshot 2020-05-27 at 10 06 07

**Comment by KadenZipfel** [comment]
> Hey @KadenZipfel do you know why the paddings on the left and right are off when testing:

Should be fixed now, thanks for pointing out.

**Comment by pimato** [comment]
@KadenZipfel great, just checked it out and it seems to be fixed. 
I have a few other things which I am gonna add here in the PR

**Comment by pimato** [comment]
clickable dapp boxes have not the same padding/margin:

Screenshot 2020-05-30 at 16 29 04

Screenshot 2020-05-30 at 16 29 10

**Comment by pimato** [comment]
burger icon is not centered vertically/horizontally:
Screenshot 2020-05-30 at 16 34 57

I´ve included a new burger icon which is centered in a box with 24x24, maybe this can help:
[burger.svg.zip](https://github.com/fMercury/dxdao-landing-page/files/4705794/burger.svg.zip)

**Comment by pimato** [comment]
Outlined buttons should be aligned to the left and right!

Currently:
Screenshot 2020-05-30 at 16 36 56

**Comment by pimato** [comment]
DXdao icon should be bigger!
Currently:
Screenshot 2020-05-30 at 16 42 05

Should:
Screenshot 2020-05-30 at 16 41 53

**Comment by pimato** [comment]
Menu items are currently using Roboto as font, but should use Source Sans Pro:
Currently:
Screenshot 2020-05-30 at 16 43 53
Should:
Screenshot 2020-05-30 at 16 44 00

**Comment by pimato** [comment]
social media icons should have some padding:
Screenshot 2020-05-30 at 16 45 31

**Comment by pimato** [comment]
all fixed. Thanks a lot @KadenZipfel !

**Pull request merged**
